
# CREAR LOS DIFERENTES NOMBRES QUE SE OBTENDRAN O DONDE SE BUSCARA LA INFORMACION 

# CREAR LOS DIFERENTES NOMBRES DONDE SE BUSCARA LA INFORMACION 
# DIAS DE ATRASO NORMAL

FECHA <- mutate(FECHA, DA=str_sub(FECHA, 3, 4), DM=str_sub(FECHA, 6, 7), DD=str_sub(FECHA, 9, 10), NEWDATE=paste(DA,DM,DD)) 
FECHA <- mutate(FECHA, NEWDAT=gsub(" ","",NEWDATE))

FECHA <- mutate(FECHA, RIESGO=paste("RIESGO_",NEWDAT)) 
FECHA <- mutate(FECHA, RIESGO=gsub(" ","",RIESGO) )

# CREAR LOS DIFERENTES NOMBRES QUE SE OBTENDRAN 
# DIAS DE ATRASO NORMAL

FECHA <- mutate(FECHA, ATRASO=paste("Atraso_Dia_",FECHA)) 
FECHA <- mutate(FECHA, ATRASO=gsub(" ","",ATRASO) )

# CREAR LOS DIFERENTES NOMBRES QUE SE OBTENDRAN 
# DIAS DE ATRASO TOTAL

FECHA <- mutate(FECHA, ATRASOT=paste("Atraso_Dia_Total_",FECHA)) 
FECHA <- mutate(FECHA, ATRASOT=gsub(" ","",ATRASOT) )

# CREAR LOS DIFERENTES NOMBRES QUE SE OBTENDRAN 
# DIAS DE VENCIDO NORMAL

FECHA <- mutate(FECHA, VENCIDO=paste("Vencido_Dia_",FECHA)) 
FECHA <- mutate(FECHA, VENCIDO=gsub(" ","",VENCIDO) )

# CREAR LOS DIFERENTES NOMBRES QUE SE OBTENDRAN 
# DIAS DE VENCIDO TOTAL

FECHA <- mutate(FECHA, VENCIDOT=paste("Vencido_Dia_Total_",FECHA)) 
FECHA <- mutate(FECHA, VENCIDOT=gsub(" ","",VENCIDOT) )





